export { Heading } from "./Heading/Heading"
export { Text } from "./Text/Text"
export { Button } from "./Button/Button"
export { Box } from "./Box/Box"
export { Input } from "./Input/Input"
export { Label } from "./Label/Label"
